import Head from 'next/head'
import { About } from './About'
import  Hero  from './Components/Hero.page'
import  Navbar  from './Components/Navbar.page'



export default function Home() {
  return (
    <div className>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Navbar />
      <Hero/>
      <About/>
     
    </div>
  )
}
