import Head from 'next/head'
import  About  from './Components/About.page'
import Contact from './Components/Contact.page'
import  Hero  from './Components/Hero.page'
import  Navbar  from './Components/Navbar.page'
import Project from './Components/Project'
import Skills from './Components/Technologies.page'



export default function Home() {
  return (
    <div className>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.webp"/>
      </Head>
      <Navbar />
      <Hero/>
      <About/>
      <Skills/>
      <Project/>
      <Contact/>
     
    </div>
  )
}
